### ISSUE TITLE
Using jupyter notebooks

### ISSUE THREAD

**Issue by adamnoach** [oj-tooth/rivercatchment#10]
[0b1d4dc](https://github.com/IRSD-Group1/rivercatchment/commit/0b1d4dc239c182b8d39834be48c61d69aed37bf8)

Your choice to use a jupyter notebook is excellent. Consider turning all files into .ipynb's?

**Comment by paultgriffiths** [comment]
estimate: four hundred minutes?

**Comment by NatanZawadzki** [comment]
Not all but some, and not today! ;)
