### ISSUE TITLE
Net-zero repository?

### ISSUE THREAD

**Issue by adamnoach** [oj-tooth/rivercatchment#14]
Have you considered off-setting the emissions derived from this repo to make it a carbon-neutral repo? Otherwise it's a great repository.

**Comment by paultgriffiths** [comment]
https://github.blog/2021-04-22-environmental-sustainability-github/#:~:text=We%20offset%20all%20emissions%20related%20to%20operating%20GitHub%2C%20including%20remote%20work. Github claims to be carbon neutral
